### negotiation roll as starter.
POST http://localhost:8080/negotiate/roll
Content-Type: application/json

{
  "lastGameId": "hello world",
  "roll": "00000",
  "demand": false
}

### negotiation roll as follower
POST http://localhost:8080/negotiate/roll
Content-Type: application/json

{
  "lastGameId": "hello world",
  "roll": "zzzzz",
  "demand": false
}

### negotiation roll with demand.
POST http://localhost:8080/negotiate/roll
Content-Type: application/json

{
  "lastGameId": "hello world",
  "roll": "00000",
  "demand": true
}

### create a game
POST http://localhost:8080/admin/games/create
Content-Type: application/json

100

